<a href="https://colab.research.google.com/github/345sarthak/Data-science-prc/blob/main/practical_1%2C2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
#Practical 1
#Write a numpy program to swap a row and col of s give array in reverse order.
#row r1=c1,c2,c3,c4
#r2=0,1,2,3,4
#r3=90,91,93,94
#r4=500,600,300
import numpy as np
a=np.array([['c1','c2','c3','c4'],[0,1,2,3,4],[90,91,93,94],[500,600,300]])
print('Orignal array:')
print(a)

Orignal array:
[list(['c1', 'c2', 'c3', 'c4']) list([0, 1, 2, 3, 4])
 list([90, 91, 93, 94]) list([500, 600, 300])]


<ipython-input-4-700b98d8867b>:8: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  a=np.array([['c1','c2','c3','c4'],[0,1,2,3,4],[90,91,93,94],[500,600,300]])


In [9]:
#Practical 1
#Write a numpy program to swap a row and col of s give array in reverse order.
#row r1=c1,c2,c3,c4
#r2=0,1,2,3,4
#r3=90,91,93,94
#r4=500,600,300,200
import numpy as np
a=np.array([['c1','c2','c3','c4'],[0,1,3,4],[90,91,93,94],[500,600,300,200]])
print('Orignal array:')
print(a)

Orignal array:
[['c1' 'c2' 'c3' 'c4']
 ['0' '1' '3' '4']
 ['90' '91' '93' '94']
 ['500' '600' '300' '200']]


In [10]:
print("\\swap the row of the said array in revers order:")
swap_row=a[::,::-1]
print(swap_row)

\swap the row of the said array in revers order:
[['c4' 'c3' 'c2' 'c1']
 ['4' '3' '1' '0']
 ['94' '93' '91' '90']
 ['200' '300' '600' '500']]


In [14]:
print("\\swap the column of the said array in revers order:")
swap_column=a[::,::-1]
print(swap_column)

\swap the row of the said array in revers order:
[['c4' 'c3' 'c2' 'c1']
 ['4' '3' '1' '0']
 ['94' '93' '91' '90']
 ['200' '300' '600' '500']]


In [15]:
print("\\swap the row and column of the said array in revers order:")
swap_row_column=a[::-1,::-1]
print(swap_row_column)

\swap the row of the said array in revers order:
[['200' '300' '600' '500']
 ['94' '93' '91' '90']
 ['4' '3' '1' '0']
 ['c4' 'c3' 'c2' 'c1']]


In [16]:
print('swap 2nd and 4th')
print('Orignal array')
print(a)
a[[1,3],:]=a[[3,1],:]
print(a)

swap 2nd and 4th
Orignal array
[['c1' 'c2' 'c3' 'c4']
 ['0' '1' '3' '4']
 ['90' '91' '93' '94']
 ['500' '600' '300' '200']]
[['c1' 'c2' 'c3' 'c4']
 ['500' '600' '300' '200']
 ['90' '91' '93' '94']
 ['0' '1' '3' '4']]


In [20]:
#practical 2
#Write a numpy program to sort an given array by the nth column
import numpy as np
print('Orignal array')
arr=np.random.randint(0,20,(3,3))
print(arr)

Orignal array
[[17 17 18]
 [ 1 10  4]
 [ 9  6 19]]


In [21]:
print(arr[arr[:,1].argsort()])

[[ 9  6 19]
 [ 1 10  4]
 [17 17 18]]


In [ ]:
#Practical 2.2
#Write a numpy program to partition a given array in a specified position.

In [23]:
import numpy as np
sarth=np.array([[70,20,50,12,30,-11,60,50,40,25,35]])
print("Original array:")
print(sarth)

Original array:
[[ 70  20  50  12  30 -11  60  50  40  25  35]]


In [27]:
print("\nAfter partition on 4 the position")
print(np.partition(sarth,4))


After partition on 4 the position
[[ 12  20 -11  25  30  35  60  50  40  50  70]]
