<a href="https://colab.research.google.com/github/345sarthak/Data-science-prc/blob/main/practical_5%2C4%2C3%2C.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import pandas as pd
df=pd.DataFrame({'school_code':['s001','s002','s003','s001','s002','s004'],
      'Name':['Sarthak','Akash','Abhinay','Ritik','Kiran','Rohan'],
      'Class':['V','V','VI','VI','V','VI'],
      'Age':[20,21,23,23,34,76],
      'Height':[125,142,124,134,124,315],
      'Weight':[69,60,45,56,67,34],
      'Address':['Nagar','Panvel','Kamothe','Nerul','Pune','Takli']})


In [6]:
df

school_code     Name Class  Age  Height  Weight  Address
0        s001  Sarthak     V   20     125      69    Nagar
1        s002    Akash     V   21     142      60   Panvel
2        s003  Abhinay    VI   23     124      45  Kamothe
3        s001    Ritik    VI   23     134      56    Nerul
4        s002    Kiran     V   34     124      67     Pune
5        s004    Rohan    VI   76     315      34    Takli

In [8]:
grouped_single=df.groupby("school_code").agg({'Age':['mean','min','max']})
grouped_single

Age        
             mean min max
school_code              
s001         21.5  20  23
s002         27.5  21  34
s003         23.0  23  23
s004         76.0  76  76

In [12]:
#Practical 5
multiple_groups=df.groupby(['school_code','Class']).agg({'Height':['mean','min','max'],'Weight':['sum','min','count']})
print(multiple_groups)

                  Height           Weight          
                    mean  min  max    sum min count
school_code Class                                  
s001        V      125.0  125  125     69  69     1
            VI     134.0  134  134     56  56     1
s002        V      133.0  124  142    127  60     2
s003        VI     124.0  124  124     45  45     1
s004        VI     315.0  315  315     34  34     1


In [13]:
#practical 3
array=[[1,2,3],[4,5,6]]
array

[[1, 2, 3], [4, 5, 6]]

In [15]:
#Write a numpy program to get a copy of matrix with element below the kth diagolan zero.
import numpy as np
m=np.matrix([[1,2,3],[4,5,6],[7,8,9]])
print(np.triu(m))


[[1 2 3]
 [0 5 6]
 [0 0 9]]
